### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by olback** [olback/buzz-waybar#2]
- [ ] Readme
- [ ] Reconnect on failure
- [ ] Fix https://github.com/olback/buzz-waybar/blob/master/src/config.rs#L45
- [ ] Remove https://github.com/olback/buzz-waybar/blob/master/src/fetch.rs#L98
